### ISSUE TITLE
Czech translation cs_CZ

### ISSUE THREAD

**Issue by singha-cz** [Zemanta/search-everything-wp-plugin#119]
Hi there, 
just to let you know, I've just sent my czech translation to you via e-mail.

**Comment by ddksr** [comment]
Hi, where did you send it?

**Comment by singha-cz** [comment]
Hi,

I have sent it to zemanta support. Also got an answer from someone thanking me for the contribution. 

Why?

 

 

 

– RK

 

TIP: Pokud se vám v prohlížeči nezobrazuje aktuální verze stránky, načtěte ji znovu stisknutím kombinace kláves CTRL+F5.

TIP: If your browser isn’t showing the latest version of a requested page, hit CTRL+F5 to refresh it.

**Comment by ddksr** [comment]
Great, 
thank you! I will try to include it in the next release.
